// Compliance standard definitions and per-control checks.
// Pure module: no network, no DOM. The credential never leaves this process.
// Ported from the V2 ruleset (lib/compliance.js @ 2e03200) with updated citations.

export type CredentialAnalysis = {
  length: number;
  hasUpper: boolean;
  hasLower: boolean;
  hasDigit: boolean;
  hasSymbol: boolean;
  classCount: number;
  entropyBits: number;
  hasRepeatRun: boolean; // aaa / 111
  hasSequence: boolean; // abc / 321 / qwe
  dictionaryHits: string[]; // wordlist words >= 4 chars found inside the credential
  mode: "password" | "passphrase";
  wordCount?: number;
};

export type ControlResult = {
  id: string;
  label: string;
  requirement: string;
  ref: string;
  pass: boolean;
  detail: string;
};

export type StandardResult = {
  id: StandardId;
  label: string;
  shortLabel: string;
  locked: boolean;
  verdict: "pass" | "fail";
  passed: number;
  total: number;
  controls: ControlResult[];
};

type ControlDef = {
  id: string;
  label: string;
  requirement: string;
  ref: string;
  check: (a: CredentialAnalysis) => { pass: boolean; detail: string };
};

export type StandardId = "NIST-800-63B" | "SOC2" | "HIPAA" | "PCI-DSS-v4";

type StandardDef = {
  id: StandardId;
  label: string;
  shortLabel: string;
  locked: boolean; // locked = verdict computed locally, control detail gated (Pro)
  description: string;
  controls: ControlDef[];
};

const fmtBits = (b: number) => `${b.toFixed(1)} bits`;

const classDetail = (a: CredentialAnalysis) =>
  [
    a.hasUpper ? "upper" : null,
    a.hasLower ? "lower" : null,
    a.hasDigit ? "digit" : null,
    a.hasSymbol ? "symbol" : null,
  ]
    .filter(Boolean)
    .join(" + ") || "none";

export const STANDARDS: StandardDef[] = [
  {
    id: "NIST-800-63B",
    label: "NIST SP 800-63B",
    shortLabel: "NIST",
    locked: false,
    description:
      "Memorized secret guidance for US federal systems. Length over forced complexity.",
    controls: [
      {
        id: "nist-length",
        label: "Minimum length",
        requirement: "8 characters or more",
        ref: "SP 800-63B §5.1.1.2",
        check: (a) => ({
          pass: a.length >= 8,
          detail: `${a.length} characters`,
        }),
      },
      {
        id: "nist-range",
        label: "Accepted range",
        requirement: "Up to 64 characters accepted, no truncation",
        ref: "SP 800-63B §5.1.1.2",
        check: (a) => ({
          pass: a.length <= 64,
          detail: a.length <= 64 ? "within 8–64 range" : `${a.length} exceeds 64`,
        }),
      },
      {
        id: "nist-entropy",
        label: "Effective entropy",
        requirement: "70 bits or more for generated secrets",
        ref: "SP 800-63B Appendix A",
        check: (a) => ({
          pass: a.entropyBits >= 70,
          detail: fmtBits(a.entropyBits),
        }),
      },
      {
        id: "nist-dictionary",
        label: "Dictionary screening",
        requirement: "No dictionary words embedded (password mode)",
        ref: "SP 800-63B §5.1.1.2",
        check: (a) =>
          a.mode === "passphrase"
            ? {
                pass: true,
                detail: "wordlist-based by design; entropy carried by word count",
              }
            : {
                pass: a.dictionaryHits.length === 0,
                detail:
                  a.dictionaryHits.length === 0
                    ? "no wordlist matches"
                    : `contains "${a.dictionaryHits[0]}"`,
              },
      },
      {
        id: "nist-patterns",
        label: "Pattern resistance",
        requirement: "No repeated runs or sequential patterns",
        ref: "SP 800-63B §5.1.1.2",
        check: (a) => ({
          pass: !a.hasRepeatRun && !a.hasSequence,
          detail:
            !a.hasRepeatRun && !a.hasSequence
              ? "no runs, no sequences"
              : a.hasRepeatRun
                ? "repeated character run found"
                : "sequential pattern found",
        }),
      },
      {
        id: "nist-source",
        label: "Random source",
        requirement: "Generated by an approved CSPRNG",
        ref: "SP 800-63B §5.1.1.1",
        check: () => ({
          pass: true,
          detail: "crypto.getRandomValues, in-browser",
        }),
      },
    ],
  },
  {
    id: "SOC2",
    label: "SOC 2 (Security TSC)",
    shortLabel: "SOC 2",
    locked: true,
    description:
      "Logical access controls with evidence retention. The certificate is the audit artifact.",
    controls: [
      {
        id: "soc2-length",
        label: "Minimum length",
        requirement: "16 characters or more",
        ref: "SOC 2 CC6.1",
        check: (a) => ({ pass: a.length >= 16, detail: `${a.length} characters` }),
      },
      {
        id: "soc2-classes",
        label: "Character diversity",
        requirement: "All four character classes",
        ref: "SOC 2 CC6.1",
        check: (a) => ({ pass: a.classCount === 4, detail: classDetail(a) }),
      },
      {
        id: "soc2-entropy",
        label: "Effective entropy",
        requirement: "80 bits or more",
        ref: "SOC 2 CC6.1 (policy baseline)",
        check: (a) => ({ pass: a.entropyBits >= 80, detail: fmtBits(a.entropyBits) }),
      },
      {
        id: "soc2-evidence",
        label: "Evidence retention",
        requirement: "Verifiable audit trail for credential issuance",
        ref: "SOC 2 CC6.1 / CC7.2",
        check: () => ({
          pass: true,
          detail: "signed certificate, verifiable at /cert/[id]",
        }),
      },
    ],
  },
  {
    id: "HIPAA",
    label: "HIPAA Security Rule",
    shortLabel: "HIPAA",
    locked: true,
    description: "Password management safeguards for systems handling PHI.",
    controls: [
      {
        id: "hipaa-length",
        label: "Minimum length",
        requirement: "12 characters or more",
        ref: "45 CFR §164.308(a)(5)(ii)(D)",
        check: (a) => ({ pass: a.length >= 12, detail: `${a.length} characters` }),
      },
      {
        id: "hipaa-classes",
        label: "Character diversity",
        requirement: "All four character classes",
        ref: "§164.308(a)(5)(ii)(D) (policy baseline)",
        check: (a) => ({ pass: a.classCount === 4, detail: classDetail(a) }),
      },
      {
        id: "hipaa-dictionary",
        label: "Dictionary screening",
        requirement: "No embedded dictionary words",
        ref: "§164.308(a)(5)(ii)(D) (policy baseline)",
        check: (a) =>
          a.mode === "passphrase"
            ? { pass: a.entropyBits >= 60, detail: "passphrase: entropy floor 60 bits applies" }
            : {
                pass: a.dictionaryHits.length === 0,
                detail:
                  a.dictionaryHits.length === 0
                    ? "no wordlist matches"
                    : `contains "${a.dictionaryHits[0]}"`,
              },
      },
    ],
  },
  {
    id: "PCI-DSS-v4",
    label: "PCI DSS v4.0",
    shortLabel: "PCI",
    locked: true,
    description: "Authentication requirements for cardholder data environments.",
    controls: [
      {
        id: "pci-length",
        label: "Minimum length",
        requirement: "12 characters or more",
        ref: "PCI DSS v4.0 Req 8.3.6",
        check: (a) => ({ pass: a.length >= 12, detail: `${a.length} characters` }),
      },
      {
        id: "pci-alphanum",
        label: "Composition",
        requirement: "Both numeric and alphabetic characters",
        ref: "PCI DSS v4.0 Req 8.3.6",
        check: (a) => ({
          pass: a.hasDigit && (a.hasUpper || a.hasLower),
          detail: classDetail(a),
        }),
      },
      {
        id: "pci-entropy",
        label: "Effective entropy",
        requirement: "40 bits or more",
        ref: "PCI DSS v4.0 Req 8.3.6 (guidance)",
        check: (a) => ({ pass: a.entropyBits >= 40, detail: fmtBits(a.entropyBits) }),
      },
      {
        id: "pci-repeats",
        label: "Repeat resistance",
        requirement: "No repeated character runs",
        ref: "PCI DSS v4.0 Req 8.3.6 (guidance)",
        check: (a) => ({
          pass: !a.hasRepeatRun,
          detail: a.hasRepeatRun ? "repeated run found" : "no runs",
        }),
      },
    ],
  },
];

export function evaluateStandards(a: CredentialAnalysis): StandardResult[] {
  return STANDARDS.map((s) => {
    const controls = s.controls.map((c) => {
      const { pass, detail } = c.check(a);
      return { id: c.id, label: c.label, requirement: c.requirement, ref: c.ref, pass, detail };
    });
    const passed = controls.filter((c) => c.pass).length;
    return {
      id: s.id,
      label: s.label,
      shortLabel: s.shortLabel,
      locked: s.locked,
      verdict: passed === controls.length ? ("pass" as const) : ("fail" as const),
      passed,
      total: controls.length,
      controls,
    };
  });
}
